/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import app.App;
import db.DAOManager;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Usuario;
import model.tm.TMUsuario;

/**
 *
 * @author luisr
 */
public class AdminPersonal extends javax.swing.JPanel {
    
    private App app;
    DAOManager dao = new DAOManager();
    public AdminPersonal(App appTemp) {
        initComponents();
        app = appTemp;
    }
    public void actualizarTabla(){
        try {
            ArrayList<Usuario> usuarios = dao.getDataUsuario().getEmpleados();
            TMUsuario tm = new TMUsuario(usuarios);
            tablaPersonal.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        panelTablaEmpleado = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaPersonal = new javax.swing.JTable();
        panelBtnAgregarEmpleado = new javax.swing.JPanel();
        btnAgregarEmpleado = new javax.swing.JLabel();
        barraBuscarEmpleado = new javax.swing.JTextField();
        nombreEmpleadoLabrel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(740, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("PERSONAL");
        add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelTablaEmpleado.setBackground(new java.awt.Color(136, 184, 158));
        panelTablaEmpleado.setPreferredSize(new java.awt.Dimension(740, 480));
        panelTablaEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPersonal.setBackground(new java.awt.Color(136, 184, 158));
        tablaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaPersonalMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tablaPersonal);

        panelTablaEmpleado.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 750, 356));

        panelBtnAgregarEmpleado.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnAgregarEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnAgregarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBtnAgregarEmpleadoMouseClicked(evt);
            }
        });

        btnAgregarEmpleado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnAgregarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarEmpleado.setText("Agregar Empleado");
        btnAgregarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarEmpleadoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnAgregarEmpleadoLayout = new javax.swing.GroupLayout(panelBtnAgregarEmpleado);
        panelBtnAgregarEmpleado.setLayout(panelBtnAgregarEmpleadoLayout);
        panelBtnAgregarEmpleadoLayout.setHorizontalGroup(
            panelBtnAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelBtnAgregarEmpleadoLayout.setVerticalGroup(
            panelBtnAgregarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelTablaEmpleado.add(panelBtnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 4, -1, 30));

        barraBuscarEmpleado.setText("buscar");
        barraBuscarEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barraBuscarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                barraBuscarEmpleadoMouseReleased(evt);
            }
        });
        barraBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraBuscarEmpleadoActionPerformed(evt);
            }
        });
        barraBuscarEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barraBuscarEmpleadoKeyTyped(evt);
            }
        });
        panelTablaEmpleado.add(barraBuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 4, 460, 30));

        nombreEmpleadoLabrel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nombreEmpleadoLabrel.setText("Nickname:");
        panelTablaEmpleado.add(nombreEmpleadoLabrel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 70, 30));

        add(panelTablaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void barraBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBuscarEmpleadoActionPerformed
        barraBuscarEmpleado.setText("");
    }//GEN-LAST:event_barraBuscarEmpleadoActionPerformed

    private void panelBtnAgregarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtnAgregarEmpleadoMouseClicked
        app.setPanelCustom(new AgregarEmpleado(app));
    }//GEN-LAST:event_panelBtnAgregarEmpleadoMouseClicked

    private void btnAgregarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoMouseClicked
        if(app.getSesionActiva().getNivelAcceso()> 2){
            app.setPanelCustom(new AgregarEmpleado(app));
        }
        else{
            String [] arreglo= {"Ok"};
            int opcion = JOptionPane.showOptionDialog(null, "No tienes permiso para esta funcion", "Acceso Denegado", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
                
//        System.out.println("no tiene el nivel de acceso requerido");
            
        }
    }//GEN-LAST:event_btnAgregarEmpleadoMouseClicked

    private void tablaPersonalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPersonalMouseReleased
        try {
            int item = tablaPersonal.getSelectedRow();
            int id = (int) tablaPersonal.getValueAt(item, 0);
            Usuario usuario = dao.getDataUsuario().obtenerUsuario(id);
            MostrarEmpleado mostrarEmpleado = new MostrarEmpleado(app);
            app.setPanelCustom(mostrarEmpleado);
            mostrarEmpleado.setCampos(usuario);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablaPersonalMouseReleased

    private void barraBuscarEmpleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraBuscarEmpleadoMouseReleased
        barraBuscarEmpleado.setText("");
    }//GEN-LAST:event_barraBuscarEmpleadoMouseReleased

    private void barraBuscarEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraBuscarEmpleadoKeyTyped
        try {
            ArrayList<Usuario> usuarios = dao.getDataUsuario().filtoNickname(barraBuscarEmpleado.getText());
            TMUsuario tm = new TMUsuario(usuarios);
            tablaPersonal.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_barraBuscarEmpleadoKeyTyped

    private void btnAgregarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoMouseEntered
        panelBtnAgregarEmpleado.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnAgregarEmpleadoMouseEntered

    private void btnAgregarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoMouseExited
        panelBtnAgregarEmpleado.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnAgregarEmpleadoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBuscarEmpleado;
    private javax.swing.JLabel btnAgregarEmpleado;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nombreEmpleadoLabrel;
    private javax.swing.JPanel panelBtnAgregarEmpleado;
    private javax.swing.JPanel panelTablaEmpleado;
    private javax.swing.JTable tablaPersonal;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
