/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Usuario;
import model.Validaciones;

/**
 *
 * @author luisr
 */
public class AgregarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form AgregarEmpleado
     */
    DAOManager dao = new DAOManager();
    Validaciones validacion = new Validaciones();
    App app;
    public AgregarEmpleado(App appTemp) {
        initComponents();
        app = appTemp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelRut = new javax.swing.JLabel();
        labelNickname = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        panelBtnVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        panelBtnAgregar = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JLabel();
        nombreEmpleado = new javax.swing.JTextField();
        apellidoEmpleado = new javax.swing.JTextField();
        nicknameEmpleado = new javax.swing.JTextField();
        labelClave1 = new javax.swing.JLabel();
        labelClave2 = new javax.swing.JLabel();
        rutEmpleado = new javax.swing.JTextField();
        clave1 = new javax.swing.JPasswordField();
        clave2 = new javax.swing.JPasswordField();
        msm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("AGREGAR EMPLEADO");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelInferior.setBackground(new java.awt.Color(136, 184, 158));
        panelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelNombre.setText("Nombre:");
        panelInferior.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 30));

        labelRut.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelRut.setText("Rut:");
        panelInferior.add(labelRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 47, 30));

        labelNickname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelNickname.setText("Nickname:");
        panelInferior.add(labelNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 73, 30));

        labelApellido.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelApellido.setText("Apellido:");
        panelInferior.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 65, 30));

        panelBtnVolver.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnVolverLayout = new javax.swing.GroupLayout(panelBtnVolver);
        panelBtnVolver.setLayout(panelBtnVolverLayout);
        panelBtnVolverLayout.setHorizontalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnVolverLayout.setVerticalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 300, 150, 30));

        panelBtnAgregar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAgregar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setText("AGREGAR");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnAgregarLayout = new javax.swing.GroupLayout(panelBtnAgregar);
        panelBtnAgregar.setLayout(panelBtnAgregarLayout);
        panelBtnAgregarLayout.setHorizontalGroup(
            panelBtnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnAgregarLayout.setVerticalGroup(
            panelBtnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 300, 150, 30));

        nombreEmpleado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        nombreEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        nombreEmpleado.setText("Juan");
        nombreEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombreEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreEmpleadoMouseClicked(evt);
            }
        });
        nombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEmpleadoActionPerformed(evt);
            }
        });
        nombreEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreEmpleadoKeyTyped(evt);
            }
        });
        panelInferior.add(nombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 210, 30));

        apellidoEmpleado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        apellidoEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        apellidoEmpleado.setText("Perez");
        apellidoEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        apellidoEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apellidoEmpleadoMouseClicked(evt);
            }
        });
        apellidoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoEmpleadoKeyTyped(evt);
            }
        });
        panelInferior.add(apellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, 30));

        nicknameEmpleado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        nicknameEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        nicknameEmpleado.setText("username");
        nicknameEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nicknameEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nicknameEmpleadoMouseClicked(evt);
            }
        });
        nicknameEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameEmpleadoActionPerformed(evt);
            }
        });
        panelInferior.add(nicknameEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, 30));

        labelClave1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelClave1.setText("Clave:");
        panelInferior.add(labelClave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 60, 30));

        labelClave2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelClave2.setText("Confirmar Clave:");
        panelInferior.add(labelClave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 110, 30));

        rutEmpleado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        rutEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        rutEmpleado.setText("25569152-k");
        rutEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rutEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rutEmpleadoMouseClicked(evt);
            }
        });
        panelInferior.add(rutEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 240, 30));

        clave1.setText("jPasswordField1");
        clave1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(clave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 240, 30));

        clave2.setText("jPasswordField2");
        clave2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(clave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 180, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelInferior.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEmpleadoMouseClicked

    private void nombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEmpleadoActionPerformed

    private void nombreEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreEmpleadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEmpleadoKeyTyped

    private void apellidoEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidoEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoEmpleadoMouseClicked

    private void apellidoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoEmpleadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoEmpleadoKeyTyped

    private void nicknameEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nicknameEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameEmpleadoMouseClicked

    private void nicknameEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameEmpleadoActionPerformed

    private void rutEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rutEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rutEmpleadoMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        try {
            String nombre = nombreEmpleado.getText();
            String apellido = apellidoEmpleado.getText();
            String nickname = nicknameEmpleado.getText();
            String rut = rutEmpleado.getText();
            String clave1 = String.valueOf(this.clave1.getPassword());
            String clave2 = String.valueOf(this.clave2.getPassword());
            if(nombre.isEmpty() || apellido.isEmpty() || nickname.isEmpty() || rut.isEmpty()){
                msm.setForeground(Color.red);
                msm.setText("Los campos no pueden estar vacios");
            }
            else if(!validacion.validarClaves(clave1, clave2)){
                msm.setForeground(Color.red);
                msm.setText("las claves no son iguales o no cumplen el minimo de 7 dijitos");
            }
            else if(!validacion.validarRut(rut)){
                msm.setForeground(Color.red);
                msm.setText("el rut es invalido");
            }
            else if(!validacion.validarNickname(nickname)){
                msm.setForeground(Color.red);
                msm.setText("el nombre de usuario ya existe intente con otro");
            }
            else{
                msm.setForeground(Color.blue);
                msm.setText("Empleado agregado con exito");
                Usuario usuario = new Usuario(0, nickname, nombre, apellido, clave1, 2, rut);
                dao.getDataUsuario().agregar(usuario);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AgregarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        AdminPersonal admin = new AdminPersonal(app);
        app.setPanelCustom(admin);
        admin.actualizarTabla();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        panelBtnVolver.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        panelBtnVolver.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        panelBtnAgregar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        panelBtnAgregar.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnAgregarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoEmpleado;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JPasswordField clave1;
    private javax.swing.JPasswordField clave2;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelClave1;
    private javax.swing.JLabel labelClave2;
    private javax.swing.JLabel labelNickname;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel msm;
    private javax.swing.JTextField nicknameEmpleado;
    private javax.swing.JTextField nombreEmpleado;
    private javax.swing.JPanel panelBtnAgregar;
    private javax.swing.JPanel panelBtnVolver;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JTextField rutEmpleado;
    // End of variables declaration//GEN-END:variables
}
