/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Libro;

/**
 *
 * @author Jorda
 */
public class DetallesLibroEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form DetallesLibroEmpleado
     */
    App app;
    Libro libro;
    DAOManager dao = new DAOManager();
    public DetallesLibroEmpleado(App appTemp) {
        initComponents();
        app = appTemp;
    }
    public void setCampos(Libro libro){
        this.libro = libro;
        jLabel15.setText(libro.getTitulo());
        labelAutor.setText("Autor: "+libro.getAutor());
        labelCategoria.setText("Categoria: "+ libro.getCategoria());
        Descripcion.setText(libro.getDescripcion());
        labelStock.setText("Stock: "+ libro.getStock());
        labelIsbn.setText("ISBN: "+ libro.getIsbn());
        labelFechapublicacion.setText("Fecha Publicacion: "+ libro.getFechaPublicacion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        labelStock = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelFechapublicacion = new javax.swing.JLabel();
        panelBtnVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        panelBtnModificar = new javax.swing.JPanel();
        btnModificar = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        labelAutor = new javax.swing.JLabel();
        labelIsbn = new javax.swing.JLabel();
        panelBtnEliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JLabel();
        msm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(152, 235, 161));
        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TITULO");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelInferior.setBackground(new java.awt.Color(136, 184, 158));
        panelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStock.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelStock.setText("Stock: stock");
        panelInferior.add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 30));

        labelDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelDescripcion.setText("Descripcion");
        panelInferior.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, 160, 30));

        labelCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelCategoria.setText("Categoria: categoria");
        panelInferior.add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 160, 30));

        labelFechapublicacion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelFechapublicacion.setText("Fecha publicacion: fecha");
        panelInferior.add(labelFechapublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 30));

        panelBtnVolver.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnVolverLayout = new javax.swing.GroupLayout(panelBtnVolver);
        panelBtnVolver.setLayout(panelBtnVolverLayout);
        panelBtnVolverLayout.setHorizontalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnVolverLayout.setVerticalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, 30));

        panelBtnModificar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModificar.setText("MODIFICAR LIBRO");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnModificarLayout = new javax.swing.GroupLayout(panelBtnModificar);
        panelBtnModificar.setLayout(panelBtnModificarLayout);
        panelBtnModificarLayout.setHorizontalGroup(
            panelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnModificarLayout.setVerticalGroup(
            panelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 150, 30));

        Descripcion.setEditable(false);
        Descripcion.setBackground(new java.awt.Color(136, 184, 158));
        Descripcion.setColumns(20);
        Descripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Descripcion.setRows(5);
        Descripcion.setBorder(null);
        scrollDescripcion.setViewportView(Descripcion);

        panelInferior.add(scrollDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 650, 90));

        labelAutor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelAutor.setText("Autor: autor");
        panelInferior.add(labelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 30));

        labelIsbn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelIsbn.setText("ISBN: isbn");
        panelInferior.add(labelIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 160, 30));

        panelBtnEliminar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.setText("ELIMINAR LIBRO");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnEliminarLayout = new javax.swing.GroupLayout(panelBtnEliminar);
        panelBtnEliminar.setLayout(panelBtnEliminarLayout);
        panelBtnEliminarLayout.setHorizontalGroup(
            panelBtnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnEliminarLayout.setVerticalGroup(
            panelBtnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelInferior.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        ModificarLibro modificar = new ModificarLibro(app);
        app.setPanelCustom(modificar);
        modificar.setCampos(libro);
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        InventarioEmpleado inventario = new InventarioEmpleado(app);
        app.setPanelCustom(inventario);
        inventario.actualizarTabla();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            String [] arreglo= {"No Eliminar", "Eliminar"};
            int opcion = JOptionPane.showOptionDialog(null, "Esta accion elimirnara todo el stock", "Eliminar Libro", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
            if(opcion == 1){
                dao.getDataLibros().eliminar(libro.getIdLibro());
                msm.setForeground(Color.blue);
                msm.setText("se elimino con exito");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetallesLibroEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        panelBtnVolver.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        panelBtnVolver.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        panelBtnEliminar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        panelBtnEliminar.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        panelBtnModificar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        panelBtnModificar.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnModificarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFechapublicacion;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel msm;
    private javax.swing.JPanel panelBtnEliminar;
    private javax.swing.JPanel panelBtnModificar;
    private javax.swing.JPanel panelBtnVolver;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JScrollPane scrollDescripcion;
    // End of variables declaration//GEN-END:variables
}
