/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package app.forms;

import app.App;
import db.DAOManager;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Libro;

/**
 *
 * @author Jorda
 */
public class Detalleslibro extends javax.swing.JPanel {
    
    /** Creates new form Detalleslibro */
    App app;
    Libro libro;
    DAOManager dao = new DAOManager();
    public Detalleslibro(App appTemp) {
        initComponents();
        app = appTemp;
    }
    public void setLibro(Libro libro){
        this.libro = libro;
        labelStock.setText("Stock: "+libro.getStock());
        labelTitulo.setText(libro.getTitulo());
        labelAutor.setText("Autor: "+ libro.getAutor());
        descripcion.setText(libro.getDescripcion());
        labelCategoria.setText("Categoria: "+ libro.getCategoria());
        labelIsbn.setText("ISBN: "+ libro.getIsbn());
        labelFechaPublicacion.setText("Fecha: "+ libro.getFechaPublicacion());
                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        labelStock = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelFechaPublicacion = new javax.swing.JLabel();
        panelBtnVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        panelBtnSolicitar = new javax.swing.JPanel();
        btnSolicitar = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        labelAutor = new javax.swing.JLabel();
        msm = new javax.swing.JLabel();
        labelIsbn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setBackground(new java.awt.Color(152, 235, 161));
        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("TITULO");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelInferior.setBackground(new java.awt.Color(136, 184, 158));
        panelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStock.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelStock.setText("Stock: stock");
        panelInferior.add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 30));

        labelDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelDescripcion.setText("Descripcion");
        panelInferior.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, 160, 30));

        labelCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelCategoria.setText("Categoria: categoria");
        panelInferior.add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 260, 30));

        labelFechaPublicacion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelFechaPublicacion.setText("Fecha publicacion: fecha");
        panelInferior.add(labelFechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 160, 30));

        panelBtnVolver.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnVolverLayout = new javax.swing.GroupLayout(panelBtnVolver);
        panelBtnVolver.setLayout(panelBtnVolverLayout);
        panelBtnVolverLayout.setHorizontalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnVolverLayout.setVerticalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 300, 150, 30));

        panelBtnSolicitar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnSolicitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnSolicitar.setForeground(new java.awt.Color(255, 255, 255));

        btnSolicitar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnSolicitar.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSolicitar.setText("SOLICITAR LIBRO");
        btnSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnSolicitarLayout = new javax.swing.GroupLayout(panelBtnSolicitar);
        panelBtnSolicitar.setLayout(panelBtnSolicitarLayout);
        panelBtnSolicitarLayout.setHorizontalGroup(
            panelBtnSolicitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSolicitar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnSolicitarLayout.setVerticalGroup(
            panelBtnSolicitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSolicitar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 300, 150, 30));

        descripcion.setEditable(false);
        descripcion.setBackground(new java.awt.Color(136, 184, 158));
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        descripcion.setRows(5);
        descripcion.setBorder(null);
        scrollDescripcion.setViewportView(descripcion);

        panelInferior.add(scrollDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 650, 120));

        labelAutor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelAutor.setText("Autor: autor");
        panelInferior.add(labelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelInferior.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        labelIsbn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelIsbn.setText("ISBN: isbn");
        panelInferior.add(labelIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, 30));

        add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        SolicitarLibro solicitarLibro = new SolicitarLibro(app);
        app.setPanelCustom2(solicitarLibro);
        solicitarLibro.actualizarTabla();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseClicked
        try {
            ArrayList<Libro> libros = dao.getUsuarioLibro().getLibrosPorUsuario(app.getSesionActiva().getId());
            
            if(libros.size()>10){
                msm.setForeground(Color.red);
                msm.setText("tiene mas de 10 libros solicitados ");
            }
            else if(libro.getStock()<= 0){
                msm.setForeground(Color.red);
                msm.setText("no queda stock de este libro");
            }
            else{
                dao.getUsuarioLibro().agregar(libro.getIdLibro(), app.getSesionActiva().getId());
                int stock = libro.getStock()- 1;
                libro.setStock(stock);
                dao.getDataLibros().modificar(libro);
                System.out.println(libro.toString());
                setLibro(libro);
                msm.setForeground(Color.blue);
                msm.setText("Libro solicitado con exito");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Detalleslibro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSolicitarMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        panelBtnVolver.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        panelBtnVolver.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnSolicitarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseEntered
        panelBtnSolicitar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnSolicitarMouseEntered

    private void btnSolicitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseExited
        panelBtnSolicitar.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnSolicitarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSolicitar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFechaPublicacion;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel msm;
    private javax.swing.JPanel panelBtnSolicitar;
    private javax.swing.JPanel panelBtnVolver;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JScrollPane scrollDescripcion;
    // End of variables declaration//GEN-END:variables

}
