/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package app.forms;

import app.App;
import db.DAOManager;
import java.awt.Color;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import java.util.ArrayList;
import model.Libro;

/**
 *
 * @author Jorda
 */
public class DevolverLibro extends javax.swing.JPanel {

    /** Creates new form DevolverLibro */
    App app;
    DAOManager dao = new DAOManager();
    Libro libro;
    public DevolverLibro(App appTemp) {
        initComponents();
        this.app = appTemp;
    }
    public void setLibro(Libro libro){
        this.libro = libro;
        jLabel2.setText(libro.getTitulo());
        labelAutoe.setText("Autor: "+ libro.getAutor());
        descripcion.setText(libro.getDescripcion());
        labelCategoria.setText("Categoria: "+ libro.getCategoria());
        labelIsbn.setText("ISBN: "+ libro.getIsbn());
        labelFechaPublicacion.setText("Fecha: "+ libro.getFechaPublicacion());
                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        labelIsbn = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelFechaPublicacion = new javax.swing.JLabel();
        panelBtnVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        panelBtnDevolver = new javax.swing.JPanel();
        btnDevolver = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        labelAutoe = new javax.swing.JLabel();
        msm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(749, 490));
        setPreferredSize(new java.awt.Dimension(749, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(152, 235, 161));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TITULO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelInferior.setBackground(new java.awt.Color(136, 184, 158));
        panelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIsbn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelIsbn.setText("ISBN: isbn");
        panelInferior.add(labelIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 160, 30));

        labelDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelDescripcion.setText("Descripcion");
        panelInferior.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, 160, 30));

        labelCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelCategoria.setText("Categoria: categoria");
        panelInferior.add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 160, 30));

        labelFechaPublicacion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelFechaPublicacion.setText("Fecha publicacion: fecha");
        panelInferior.add(labelFechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 160, 30));

        panelBtnVolver.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnVolverLayout = new javax.swing.GroupLayout(panelBtnVolver);
        panelBtnVolver.setLayout(panelBtnVolverLayout);
        panelBtnVolverLayout.setHorizontalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnVolverLayout.setVerticalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 300, 150, 30));

        panelBtnDevolver.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnDevolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDevolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnDevolver.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDevolver.setText("DEVOLVER LIBRO");
        btnDevolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDevolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDevolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnDevolverLayout = new javax.swing.GroupLayout(panelBtnDevolver);
        panelBtnDevolver.setLayout(panelBtnDevolverLayout);
        panelBtnDevolverLayout.setHorizontalGroup(
            panelBtnDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnDevolverLayout.setVerticalGroup(
            panelBtnDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 300, 150, 30));

        descripcion.setEditable(false);
        descripcion.setBackground(new java.awt.Color(136, 184, 158));
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        descripcion.setRows(5);
        descripcion.setBorder(null);
        scrollDescripcion.setViewportView(descripcion);

        panelInferior.add(scrollDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 650, 120));

        labelAutoe.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelAutoe.setText("Autor: autor");
        panelInferior.add(labelAutoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelInferior.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        LibrosSolicitados librosSolicitados = new LibrosSolicitados(app);
        app.setPanelCustom2(librosSolicitados);
        librosSolicitados.actualizarTabla();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseClicked
        try {
            ArrayList<Libro> libros = dao.getUsuarioLibro().getLibrosPorUsuario(app.getSesionActiva().getId());
            for (Libro libro1 : libros) {
                if (libro1.getIdLibro() == libro.getIdLibro()){
                    int stock = libro.getStock()+ 1;
                    libro.setStock(stock);
                    dao.getDataLibros().modificar(libro);
                    dao.getUsuarioLibro().eliminar(app.getSesionActiva().getId(), libro.getIdLibro());
                    System.out.println(libro.toString());
                    msm.setForeground(Color.blue);
                    msm.setText("Devolucion hecha");
                    break;
                    
                }
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(DevolverLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
        

    }//GEN-LAST:event_btnDevolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        panelBtnVolver.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        panelBtnVolver.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnDevolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseEntered
        panelBtnDevolver.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnDevolverMouseEntered

    private void btnDevolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseExited
        panelBtnDevolver.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnDevolverMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDevolver;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAutoe;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFechaPublicacion;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel msm;
    private javax.swing.JPanel panelBtnDevolver;
    private javax.swing.JPanel panelBtnVolver;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JScrollPane scrollDescripcion;
    // End of variables declaration//GEN-END:variables

}
