/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Libro;
import model.tm.TMLibros;

/**
 *
 * @author luisr
 */
public class InventarioEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form InventarioEmpleado
     */
    DAOManager dao = new DAOManager();
    App app;
    public InventarioEmpleado(App appTemp) {
        initComponents();
        app = appTemp;
    }
    public void actualizarTabla(){
        try {
            ArrayList<Libro> libros = dao.getDataLibros().getLibros();
            TMLibros tm = new TMLibros(libros);
            tablaInventario.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(InventarioEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoInventario = new javax.swing.JPanel();
        labelSubtitulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        txtTitulo = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(750, 490));
        setPreferredSize(new java.awt.Dimension(750, 490));

        panelFondoInventario.setBackground(new java.awt.Color(255, 255, 255));
        panelFondoInventario.setMinimumSize(new java.awt.Dimension(750, 490));
        panelFondoInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSubtitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        labelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo.setText("INVENTARIO");
        panelFondoInventario.add(labelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelInferior.setBackground(new java.awt.Color(136, 184, 158));
        panelInferior.setPreferredSize(new java.awt.Dimension(750, 480));

        tablaInventario.setBackground(new java.awt.Color(136, 184, 158));
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaInventarioMouseReleased(evt);
            }
        });
        scrollTable.setViewportView(tablaInventario);

        txtTitulo.setText("Titulo");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });

        labelNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelNombre.setText("Nombre:");

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFondoInventario.add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void tablaInventarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioMouseReleased
        try {
            int item = tablaInventario.getSelectedRow();
            int id = (int) tablaInventario.getValueAt(item, 0);
            Libro libro = dao.getDataLibros().obtenerLibro(id);
            DetallesLibroEmpleado libroEmpleado = new DetallesLibroEmpleado(app);
            app.setPanelCustom(libroEmpleado);
            libroEmpleado.setCampos(libro);
            System.out.println(libro.toString());
        } catch (SQLException ex) {
            Logger.getLogger(InventarioEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablaInventarioMouseReleased

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
        try {
            ArrayList<Libro> libros = dao.getDataLibros().filtroTitulo(txtTitulo.getText());
            TMLibros tm = new TMLibros(libros);
            tablaInventario.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(InventarioEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTituloKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JPanel panelFondoInventario;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
