/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Libro;
import model.tm.TMLibros;

/**
 *
 * @author aniba
 */
public class LibrosSolicitados extends javax.swing.JPanel {

    DAOManager dao = new DAOManager();
    App app;
    public LibrosSolicitados(App appTemp) {
        initComponents();
        this.app = appTemp;
    }
    public void actualizarTabla(){
        try {
            ArrayList<Libro> libro = dao.getUsuarioLibro().getLibrosPorUsuario(app.getSesionActiva().getId());
            TMLibros tm = new TMLibros(libro);
            tablaLibrosSolicitados.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(LibrosSolicitados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTable = new javax.swing.JScrollPane();
        tablaLibrosSolicitados = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(740, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollTable.setBackground(new java.awt.Color(152, 235, 161));

        tablaLibrosSolicitados.setBackground(new java.awt.Color(136, 184, 158));
        tablaLibrosSolicitados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaLibrosSolicitados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaLibrosSolicitadosMouseReleased(evt);
            }
        });
        scrollTable.setViewportView(tablaLibrosSolicitados);

        add(scrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 750, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaLibrosSolicitadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibrosSolicitadosMouseReleased
        try {
            int item = tablaLibrosSolicitados.getSelectedRow();
            int id = (int) tablaLibrosSolicitados.getValueAt(item, 0);
            Libro libro = dao.getDataLibros().obtenerLibro(id);
            DevolverLibro devolver = new DevolverLibro(app);
            app.setPanelCustom2(devolver);
            devolver.setLibro(libro);
            System.out.println(libro.toString());
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablaLibrosSolicitadosMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tablaLibrosSolicitados;
    // End of variables declaration//GEN-END:variables
}
