/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Libro;
import model.Validaciones;

/**
 *
 * @author Jorda
 */
public class ModificarLibro extends javax.swing.JPanel {

    /**
     * Creates new form ModificarLibro
     */
    App app;
    Libro libro;
    DAOManager dao = new DAOManager();
    Validaciones validacion = new Validaciones();
    public ModificarLibro(App appTemp) {
        initComponents();
        app = appTemp;
    }
    public void setCampos(Libro libro){
        this.libro = libro;
        autor.setText(libro.getAutor());
        titulo.setText(libro.getTitulo());
        categoria.setSelectedItem(libro.getCategoria());
        descripcion.setText(libro.getDescripcion());
        stock.setText(""+libro.getStock());
        isbn.setText(libro.getIsbn());
        fechaPublicacion.setText(""+libro.getFechaPublicacion());
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSubtitulo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labelStock = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelFechaPublicacion = new javax.swing.JLabel();
        panelBtnVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        panelBtnGuardar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        labelAutor = new javax.swing.JLabel();
        fechaPublicacion = new javax.swing.JTextField();
        categoria = new javax.swing.JComboBox<>();
        autor = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        labelIsbn = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        msm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSubtitulo.setBackground(new java.awt.Color(152, 235, 161));
        labelSubtitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        labelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtitulo.setText("MODIFICAR LIBRO");
        add(labelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 749, 100));

        jPanel8.setBackground(new java.awt.Color(136, 184, 158));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStock.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelStock.setText("Stock: ");
        jPanel8.add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, 30));

        labelDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelDescripcion.setText("Descripcion");
        jPanel8.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, 160, 30));

        labelCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelCategoria.setText("Categoria:");
        jPanel8.add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 70, 30));

        labelFechaPublicacion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelFechaPublicacion.setText("Fecha Publicacion:");
        jPanel8.add(labelFechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 30));

        panelBtnVolver.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnVolverLayout = new javax.swing.GroupLayout(panelBtnVolver);
        panelBtnVolver.setLayout(panelBtnVolverLayout);
        panelBtnVolverLayout.setHorizontalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnVolverLayout.setVerticalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel8.add(panelBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 300, 150, 30));

        panelBtnGuardar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnGuardar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnGuardarLayout = new javax.swing.GroupLayout(panelBtnGuardar);
        panelBtnGuardar.setLayout(panelBtnGuardarLayout);
        panelBtnGuardarLayout.setHorizontalGroup(
            panelBtnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnGuardarLayout.setVerticalGroup(
            panelBtnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel8.add(panelBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 300, 150, 30));

        descripcion.setBackground(new java.awt.Color(136, 184, 158));
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        descripcion.setRows(5);
        descripcion.setBorder(null);
        scrollDescripcion.setViewportView(descripcion);

        jPanel8.add(scrollDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 652, 90));

        labelAutor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelAutor.setText("Autor:");
        jPanel8.add(labelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 30));

        fechaPublicacion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        fechaPublicacion.setText("DD-MM-YYYY");
        fechaPublicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(fechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 250, 190, 30));

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ficción", "No ficción", "Literatura clásica", "Ciencia ficción", "Fantasía", "Misterio y suspense", "Thriller", "Romántico", "Biografía y memorias", "Historia", "Ensayo", "Poesía", "Literatura juvenil", "Cuentos y relatos cortos" }));
        jPanel8.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 180, 30));

        autor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        autor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 210, 30));

        stock.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        stock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, 30));

        labelIsbn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelIsbn.setText("ISBN:");
        jPanel8.add(labelIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 40, 30));

        isbn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        isbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 200, 30));

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelTitulo.setText("Titulo:");
        jPanel8.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 60, 30));

        titulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 210, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 749, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        LocalDate fecha;
        try {
            String autor = this.autor.getText();
            String titulo = this.titulo.getText();
            String descripcion = this.descripcion.getText();
            String categoria = String.valueOf(this.categoria.getSelectedItem());
            String isbn = this.isbn.getText();
            int stock = Integer.parseInt(this.stock.getText());
            
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate fechas = LocalDate.parse(fechaPublicacion.getText(), formato);
            if(autor.isEmpty()||titulo.isEmpty()||descripcion.isEmpty()||isbn.isEmpty()||fechaPublicacion.getText().isEmpty()){
                msm.setForeground(Color.red);
                msm.setText("los campos no pueden estar vacion");
            }
            else if(!validacion.validarIsbn(isbn)){
                msm.setForeground(Color.red);
                msm.setText("el isbn es incorrecto");
            }
            else if(stock<1||this.stock.getText().isEmpty()){
                msm.setForeground(Color.red);
                msm.setText("el stock es incorrecto");
            }
            else{
                libro.setAutor(autor);
                libro.setTitulo(titulo);
                libro.setDescripcion(descripcion);
                libro.setCategoria(categoria);
                libro.setIsbn(isbn);
                libro.setStock(stock);
                libro.setFechaPublicacion(fechas);
                dao.getDataLibros().modificar(libro);
                msm.setForeground(Color.blue);
                msm.setText("Libro modificado con exito");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificarLibro.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NumberFormatException e){
            msm.setForeground(Color.red);
            msm.setText("El stock es incorrecto");
        }
        
        
        
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        DetallesLibroEmpleado detallesLibro = new DetallesLibroEmpleado(app);
        app.setPanelCustom(detallesLibro);
        detallesLibro.setCampos(libro);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        panelBtnVolver.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        panelBtnVolver.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        panelBtnGuardar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        panelBtnGuardar.setBackground(new Color(44,72,47));
    }//GEN-LAST:event_btnGuardarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autor;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JTextField fechaPublicacion;
    private javax.swing.JTextField isbn;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFechaPublicacion;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel msm;
    private javax.swing.JPanel panelBtnGuardar;
    private javax.swing.JPanel panelBtnVolver;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
