/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Usuario;
import model.Validaciones;

/**
 *
 * @author aniba
 */
public class ModificarPerfil extends javax.swing.JPanel {

    /**
     * Creates new form ModificarPerfil
     */
    App app;
    DAOManager dao = new DAOManager();
    Validaciones validacion = new Validaciones();
    public ModificarPerfil(App appTemp) {
        initComponents();
        app = appTemp;
    }
    public void setCampos(){
        Usuario usuario = app.getSesionActiva();
        nombreUsuario.setText(usuario.getNombre());
        apellidoUsuario.setText(usuario.getApellido());
        nicknameUsuario.setText(usuario.getNickname());
        clave1Usuario.setText("");
        clave2Usuario.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subtutulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        labelNicknameUsuario = new javax.swing.JLabel();
        labelApellidoUsuario = new javax.swing.JLabel();
        labelNombreUsuario = new javax.swing.JLabel();
        panelBtnVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        panelBtnModificar = new javax.swing.JPanel();
        btnModificar = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        apellidoUsuario = new javax.swing.JTextField();
        labelClave1 = new javax.swing.JLabel();
        clave1Usuario = new javax.swing.JPasswordField();
        clave2Usuario = new javax.swing.JPasswordField();
        labelClave2 = new javax.swing.JLabel();
        nicknameUsuario = new javax.swing.JTextField();
        msm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(740, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtutulo.setBackground(new java.awt.Color(255, 255, 255));
        subtutulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        subtutulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtutulo.setText("MODIFICAR PERFIL");
        add(subtutulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelInferior.setBackground(new java.awt.Color(136, 184, 158));
        panelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNicknameUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelNicknameUsuario.setText("Nuevo nickname:");
        panelInferior.add(labelNicknameUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        labelApellidoUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelApellidoUsuario.setText("Nuevo Apellido:");
        panelInferior.add(labelApellidoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        labelNombreUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelNombreUsuario.setText("Nuevo nombre:");
        panelInferior.add(labelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 30));

        panelBtnVolver.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnVolver.setPreferredSize(new java.awt.Dimension(150, 30));
        panelBtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBtnVolverMouseEntered(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnVolverLayout = new javax.swing.GroupLayout(panelBtnVolver);
        panelBtnVolver.setLayout(panelBtnVolverLayout);
        panelBtnVolverLayout.setHorizontalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnVolverLayout.setVerticalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 300, 150, 30));

        panelBtnModificar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnModificar.setPreferredSize(new java.awt.Dimension(150, 30));

        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModificar.setText("MODIFICAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnModificarLayout = new javax.swing.GroupLayout(panelBtnModificar);
        panelBtnModificar.setLayout(panelBtnModificarLayout);
        panelBtnModificarLayout.setHorizontalGroup(
            panelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnModificarLayout.setVerticalGroup(
            panelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 300, 150, 30));

        nombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 190, 30));

        apellidoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        apellidoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoUsuarioActionPerformed(evt);
            }
        });
        panelInferior.add(apellidoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, 30));

        labelClave1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelClave1.setText("Nueva Clave:");
        panelInferior.add(labelClave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, 30));

        clave1Usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(clave1Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 180, 30));

        clave2Usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(clave2Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 180, 30));

        labelClave2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelClave2.setText("Comfirmar Clave:");
        panelInferior.add(labelClave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, 30));

        nicknameUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nicknameUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameUsuarioActionPerformed(evt);
            }
        });
        panelInferior.add(nicknameUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 190, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelInferior.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        PerfilUsuario perfil = new PerfilUsuario(app);
        app.setPanelCustom2(perfil);
        perfil.setPerfil(app.getSesionActiva());
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        panelBtnVolver.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        panelBtnVolver.setBackground(new Color(42,72,47));
    }//GEN-LAST:event_btnVolverMouseExited

    private void panelBtnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtnVolverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelBtnVolverMouseEntered

    private void apellidoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoUsuarioActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        try {
            String clave1 = String.valueOf(clave1Usuario.getPassword());
            String clave2 = String.valueOf(clave2Usuario.getPassword());
            String Nickname = nicknameUsuario.getText();
            String nombre = nombreUsuario.getText();
            String apellido = apellidoUsuario.getText();
            
            if(Nickname.isEmpty()||nombre.isBlank()||apellido.isEmpty()){
                msm.setForeground(Color.red);
                msm.setText("Los campos no pueden estar vacio");
            }
            else if(!validacion.validarNickname(Nickname)){
                msm.setForeground(Color.red);
                msm.setText("El nombre de usuario ya existe");
            }
            else if(!validacion.validarClaves(clave1, clave2)){
                msm.setForeground(Color.red);
                msm.setText("Las claves no son iguales o no cumplen con el minimo de 8 digitos");
            }
            else{
                Usuario usuario = app.getSesionActiva();
                usuario.setApellido(apellidoUsuario.getText());
                usuario.setNombre(nombreUsuario.getText());
                dao.getDataUsuario().modificar(usuario);
                msm.setForeground(Color.blue);
                msm.setText("Perfil modificado con exito");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificarPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnModificarMouseClicked

    private void nicknameUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameUsuarioActionPerformed

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        panelBtnModificar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        panelBtnModificar.setBackground(new Color(42,72,44));
    }//GEN-LAST:event_btnModificarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoUsuario;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JPasswordField clave1Usuario;
    private javax.swing.JPasswordField clave2Usuario;
    private javax.swing.JLabel labelApellidoUsuario;
    private javax.swing.JLabel labelClave1;
    private javax.swing.JLabel labelClave2;
    private javax.swing.JLabel labelNicknameUsuario;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JLabel msm;
    private javax.swing.JTextField nicknameUsuario;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JPanel panelBtnModificar;
    private javax.swing.JPanel panelBtnVolver;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JLabel subtutulo;
    // End of variables declaration//GEN-END:variables
}
