/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import java.awt.Color;
import model.Usuario;

/**
 *
 * @author Jorda
 */
public class MostrarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form MostrarEmpleado
     */
    Usuario usuario;
    App app;
    public MostrarEmpleado(App appTemp) {
        initComponents();
        app = appTemp;
    }
    public void setCampos(Usuario usuario){
        this.usuario = usuario;
        labelNombre.setText("Nombre: "+usuario.getNombre());
        labelRut.setText("Rut: "+ usuario.getRut());
        labelApellido.setText("Apellido: "+ usuario.getApellido());
        labelNickname.setText("nickname: "+ usuario.getNickname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subtitulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelRut = new javax.swing.JLabel();
        labelNickname = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        panelBtnVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        panelBtnModificar = new javax.swing.JPanel();
        btnModificar = new javax.swing.JLabel();
        msm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(740, 480));
        setPreferredSize(new java.awt.Dimension(740, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("DETALLES EMPLEADO");
        add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelInferior.setBackground(new java.awt.Color(136, 184, 158));
        panelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelNombre.setText("Nombre:");
        panelInferior.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, 30));

        labelRut.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelRut.setText("Rut:");
        panelInferior.add(labelRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 250, 30));

        labelNickname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelNickname.setText("Nickname:");
        panelInferior.add(labelNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 250, 30));

        labelApellido.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelApellido.setText("Apellido:");
        panelInferior.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, 30));

        panelBtnVolver.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnVolverLayout = new javax.swing.GroupLayout(panelBtnVolver);
        panelBtnVolver.setLayout(panelBtnVolverLayout);
        panelBtnVolverLayout.setHorizontalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnVolverLayout.setVerticalGroup(
            panelBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 300, 150, 30));

        panelBtnModificar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModificar.setText("MODIFICAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnModificarLayout = new javax.swing.GroupLayout(panelBtnModificar);
        panelBtnModificar.setLayout(panelBtnModificarLayout);
        panelBtnModificarLayout.setHorizontalGroup(
            panelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnModificarLayout.setVerticalGroup(
            panelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 300, 150, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelInferior.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        ModificarEmpleado modificar = new ModificarEmpleado(app);
        app.setPanelCustom(modificar);
        modificar.setCampos(usuario);
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        AdminPersonal administrador = new AdminPersonal(app);
        app.setPanelCustom(administrador);
        administrador.actualizarTabla();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        panelBtnVolver.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        panelBtnVolver.setBackground(new Color(42,72,44));
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        panelBtnModificar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        panelBtnModificar.setBackground(new Color(42,72,44));
    }//GEN-LAST:event_btnModificarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelNickname;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel msm;
    private javax.swing.JPanel panelBtnModificar;
    private javax.swing.JPanel panelBtnVolver;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JLabel subtitulo;
    // End of variables declaration//GEN-END:variables
}
