/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import db.DAOManager;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Libro;
import model.Validaciones;

/**
 *
 * @author luisr
 */
    
public class NuevoLibro extends javax.swing.JPanel {

    /**
     * Creates new form PanelNuevoLibro
     */
    DAOManager dao = new DAOManager();
    Validaciones validacion = new Validaciones();
    public NuevoLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subtitulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        panelBtnVaciar = new javax.swing.JPanel();
        btnVaciar = new javax.swing.JLabel();
        panelBtnAgregar = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        categoria = new javax.swing.JComboBox<>();
        scrollDescripcion = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        fechaPublicacion = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        labelFechaPublicacion = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        labelIsbn = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        labelAutor = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        msm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 490));
        setPreferredSize(new java.awt.Dimension(740, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setBackground(new java.awt.Color(255, 255, 255));
        subtitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("NUEVO LIBRO");
        add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelInferior.setBackground(new java.awt.Color(136, 184, 158));
        panelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBtnVaciar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnVaciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVaciar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnVaciar.setForeground(new java.awt.Color(255, 255, 255));
        btnVaciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVaciar.setText("VACIAR");
        btnVaciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVaciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVaciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVaciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVaciarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnVaciarLayout = new javax.swing.GroupLayout(panelBtnVaciar);
        panelBtnVaciar.setLayout(panelBtnVaciarLayout);
        panelBtnVaciarLayout.setHorizontalGroup(
            panelBtnVaciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVaciar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnVaciarLayout.setVerticalGroup(
            panelBtnVaciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVaciar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 300, 150, 30));

        panelBtnAgregar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnAgregar.setPreferredSize(new java.awt.Dimension(140, 30));

        btnAgregar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setText("AGREGAR");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnAgregarLayout = new javax.swing.GroupLayout(panelBtnAgregar);
        panelBtnAgregar.setLayout(panelBtnAgregarLayout);
        panelBtnAgregarLayout.setHorizontalGroup(
            panelBtnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnAgregarLayout.setVerticalGroup(
            panelBtnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelInferior.add(panelBtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 300, 150, 30));

        autor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 210, 30));

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ficción", "No ficción", "Literatura clásica", "Ciencia ficción", "Fantasía", "Misterio y suspense", "Thriller", "Romántico", "Biografía y memorias", "Historia", "Ensayo", "Poesía", "Literatura juvenil", "Cuentos y relatos cortos" }));
        panelInferior.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 180, 30));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        scrollDescripcion.setViewportView(descripcion);

        panelInferior.add(scrollDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 652, -1));

        fechaPublicacion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        fechaPublicacion.setText("YYYY-MM-DD");
        fechaPublicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(fechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 250, 190, 30));

        isbn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 200, 30));

        labelFechaPublicacion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelFechaPublicacion.setText("Fecha Publicacion:");
        panelInferior.add(labelFechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 30));

        labelStock.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelStock.setText("Stock:");
        panelInferior.add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, 30));

        labelIsbn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelIsbn.setText("ISBN:");
        panelInferior.add(labelIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 40, 30));

        stock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, 30));

        labelCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelCategoria.setText("Categoria:");
        panelInferior.add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 70, 30));

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelTitulo.setText("Titulo");
        panelInferior.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 60, 30));

        titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInferior.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 210, 30));

        labelAutor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelAutor.setText("Autor: ");
        panelInferior.add(labelAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 30));

        labelDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelDescripcion.setText("Descripcion");
        panelInferior.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelInferior.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        LocalDate fechaFormateada = null;
        try {
            String fecha = fechaPublicacion.getText();
            fechaFormateada= validacion.validarFecha(fecha);
        } catch (Exception ex) {
            msm.setForeground(Color.red);
            msm.setText("La fecha esta incorecta");
        }
        try {
            String autor = this.autor.getText();
            String titulo = this.titulo.getText();
            String descripcion = this.descripcion.getText();
            String isbn = this.isbn.getText();
            String categoria = String.valueOf(this.categoria.getSelectedItem());
            int stock = Integer.parseInt(this.stock.getText());
            if(autor.isEmpty() || titulo.isEmpty() || descripcion.isEmpty() || isbn.isEmpty()){
                msm.setForeground(Color.red);
                msm.setText("Los campos no pueden estar vacios");
            }
            else if(!validacion.validarIsbn(isbn)){
                msm.setForeground(Color.red);
                msm.setText("El isbn es incorrecto");
            }
            else if(stock <=0 || this.stock.getText().isEmpty()){
                msm.setForeground(Color.red);
                msm.setText("ingrese un stock valido");
            }
            else{
                Libro libro = new Libro(0, titulo, autor, categoria, stock, fechaFormateada, descripcion, isbn);
                msm.setForeground(Color.blue);
                msm.setText("Libro agregado con exito");
                dao.getDataLibros().agregar(libro);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoLibro.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NumberFormatException e){
            msm.setForeground(Color.red);
            msm.setText("El Stock es incorrecto");
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnVaciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVaciarMouseClicked
        titulo.setText("");
        autor.setText("");
        isbn.setText("");
        descripcion.setText("");
        stock.setText("");
        fechaPublicacion.setText("YYYY-MM-DD");
    }//GEN-LAST:event_btnVaciarMouseClicked

    private void btnVaciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVaciarMouseEntered
        panelBtnVaciar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnVaciarMouseEntered

    private void btnVaciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVaciarMouseExited
        panelBtnVaciar.setBackground(new Color(42,72,47));
    }//GEN-LAST:event_btnVaciarMouseExited

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        panelBtnAgregar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        panelBtnAgregar.setBackground(new Color(42,72,47));
    }//GEN-LAST:event_btnAgregarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autor;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnVaciar;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JTextField fechaPublicacion;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFechaPublicacion;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel msm;
    private javax.swing.JPanel panelBtnAgregar;
    private javax.swing.JPanel panelBtnVaciar;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
