/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Usuario;

/**
 *
 * @author aniba
 */
public class PerfilUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PerfilUsuario
     */
    App app;
    public PerfilUsuario(App appTemp) {
        initComponents();
        app = appTemp;
    }
    
    public void setPerfil(Usuario usuario){
        labelIdPerfil.setText("Id Perfil: " + usuario.getId());
        labelNombre.setText("Nombre: " + usuario.getNombre());
        labelNickname.setText("Nick name: " + usuario.getNickname());
        labelApellido.setText("Apellido: " + usuario.getApellido());
        labelRut.setText("Rut: " + usuario.getRut());
        System.out.println(usuario.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subtitulo = new javax.swing.JLabel();
        panelTituloPerfil = new javax.swing.JPanel();
        labelNickname = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelIdPerfil = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelRut = new javax.swing.JLabel();
        panelBtnModificar = new javax.swing.JPanel();
        btnModificar = new javax.swing.JLabel();
        panelBtnLibrosSolicitados = new javax.swing.JPanel();
        btnLibrosSolicitados = new javax.swing.JLabel();
        panelBtnSalasSolicitadas = new javax.swing.JPanel();
        btnSalasSolicitadas = new javax.swing.JLabel();
        msm = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setBackground(new java.awt.Color(255, 255, 255));
        subtitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("PERFIL");
        add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        panelTituloPerfil.setBackground(new java.awt.Color(136, 184, 158));
        panelTituloPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNickname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelNickname.setText("Nickname:");
        panelTituloPerfil.add(labelNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 67, 250, 30));

        labelApellido.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelApellido.setText("Apellido:");
        panelTituloPerfil.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 143, 250, 30));

        labelIdPerfil.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelIdPerfil.setText("ID:");
        panelTituloPerfil.add(labelIdPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 67, 250, 30));

        labelNombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelNombre.setText("Nombre:");
        panelTituloPerfil.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 143, 250, 30));

        labelRut.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelRut.setText("Rut:");
        panelTituloPerfil.add(labelRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 250, 30));

        panelBtnModificar.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnModificar.setPreferredSize(new java.awt.Dimension(150, 30));
        panelBtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBtnModificarMouseEntered(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModificar.setText("MODIFICAR PERFIL");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnModificarLayout = new javax.swing.GroupLayout(panelBtnModificar);
        panelBtnModificar.setLayout(panelBtnModificarLayout);
        panelBtnModificarLayout.setHorizontalGroup(
            panelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnModificarLayout.setVerticalGroup(
            panelBtnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelTituloPerfil.add(panelBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, 30));

        panelBtnLibrosSolicitados.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnLibrosSolicitados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnLibrosSolicitados.setPreferredSize(new java.awt.Dimension(150, 30));

        btnLibrosSolicitados.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnLibrosSolicitados.setForeground(new java.awt.Color(255, 255, 255));
        btnLibrosSolicitados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLibrosSolicitados.setText("LIBROS SOLICITADOS");
        btnLibrosSolicitados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLibrosSolicitados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibrosSolicitadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibrosSolicitadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibrosSolicitadosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnLibrosSolicitadosLayout = new javax.swing.GroupLayout(panelBtnLibrosSolicitados);
        panelBtnLibrosSolicitados.setLayout(panelBtnLibrosSolicitadosLayout);
        panelBtnLibrosSolicitadosLayout.setHorizontalGroup(
            panelBtnLibrosSolicitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLibrosSolicitados, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        panelBtnLibrosSolicitadosLayout.setVerticalGroup(
            panelBtnLibrosSolicitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLibrosSolicitados, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelTituloPerfil.add(panelBtnLibrosSolicitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 150, 30));

        panelBtnSalasSolicitadas.setBackground(new java.awt.Color(44, 72, 47));
        panelBtnSalasSolicitadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBtnSalasSolicitadas.setPreferredSize(new java.awt.Dimension(150, 30));

        btnSalasSolicitadas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnSalasSolicitadas.setForeground(new java.awt.Color(255, 255, 255));
        btnSalasSolicitadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalasSolicitadas.setText("SALAS SOLICITADAS");
        btnSalasSolicitadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalasSolicitadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalasSolicitadasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalasSolicitadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalasSolicitadasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnSalasSolicitadasLayout = new javax.swing.GroupLayout(panelBtnSalasSolicitadas);
        panelBtnSalasSolicitadas.setLayout(panelBtnSalasSolicitadasLayout);
        panelBtnSalasSolicitadasLayout.setHorizontalGroup(
            panelBtnSalasSolicitadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnSalasSolicitadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalasSolicitadas, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBtnSalasSolicitadasLayout.setVerticalGroup(
            panelBtnSalasSolicitadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnSalasSolicitadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalasSolicitadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTituloPerfil.add(panelBtnSalasSolicitadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 150, 30));

        msm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        msm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTituloPerfil.add(msm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, -1));

        add(panelTituloPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        ModificarPerfil modificar = new ModificarPerfil(app);
        app.setPanelCustom2(modificar);
        modificar.setCampos();
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        panelBtnModificar.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        panelBtnModificar.setBackground(new Color(42,72,47));
    }//GEN-LAST:event_btnModificarMouseExited

    private void panelBtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtnModificarMouseEntered
        
    }//GEN-LAST:event_panelBtnModificarMouseEntered

    private void btnLibrosSolicitadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosSolicitadosMouseClicked
        LibrosSolicitados librosSolicitados = new LibrosSolicitados(app);
        app.setPanelCustom2(librosSolicitados);
        librosSolicitados.actualizarTabla();
    }//GEN-LAST:event_btnLibrosSolicitadosMouseClicked

    private void btnSalasSolicitadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalasSolicitadasMouseClicked
        SalasSolicitadas salasSolicitadas = new SalasSolicitadas(app);
        app.setPanelCustom2(salasSolicitadas);
        salasSolicitadas.actualizarTabla();
    }//GEN-LAST:event_btnSalasSolicitadasMouseClicked

    private void btnLibrosSolicitadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosSolicitadosMouseEntered
        panelBtnLibrosSolicitados.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnLibrosSolicitadosMouseEntered

    private void btnLibrosSolicitadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosSolicitadosMouseExited
        panelBtnLibrosSolicitados.setBackground(new Color(42,72,47));
    }//GEN-LAST:event_btnLibrosSolicitadosMouseExited

    private void btnSalasSolicitadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalasSolicitadasMouseEntered
        panelBtnSalasSolicitadas.setBackground(new Color(32,45,33));
    }//GEN-LAST:event_btnSalasSolicitadasMouseEntered

    private void btnSalasSolicitadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalasSolicitadasMouseExited
        panelBtnSalasSolicitadas.setBackground(new Color(42,72,47));
    }//GEN-LAST:event_btnSalasSolicitadasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLibrosSolicitados;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnSalasSolicitadas;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelIdPerfil;
    private javax.swing.JLabel labelNickname;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel msm;
    private javax.swing.JPanel panelBtnLibrosSolicitados;
    private javax.swing.JPanel panelBtnModificar;
    private javax.swing.JPanel panelBtnSalasSolicitadas;
    private javax.swing.JPanel panelTituloPerfil;
    private javax.swing.JLabel subtitulo;
    // End of variables declaration//GEN-END:variables
}
