/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Sala;
import model.tm.TMSalas;

/**
 *
 * @author aniba
 */
public class SalasSolicitadas extends javax.swing.JPanel {

    /**
     * Creates new form SalasSolicitadas
     */
    DAOManager dao = new DAOManager();
    App app;
    public SalasSolicitadas(App appTemp) {
        initComponents();
        this.app = appTemp;
    }
    public void actualizarTabla(){
        try {
            ArrayList<Sala> salas = dao.getUsuarioSala().salasPorUsuario(app.getSesionActiva().getId());
            TMSalas tm = new TMSalas(salas);
            tablaSalaSolicitadas.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(SalasSolicitadas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTablaSalasSolicitadas = new javax.swing.JScrollPane();
        tablaSalaSolicitadas = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollTablaSalasSolicitadas.setBackground(new java.awt.Color(136, 184, 158));
        scrollTablaSalasSolicitadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                scrollTablaSalasSolicitadasMouseReleased(evt);
            }
        });

        tablaSalaSolicitadas.setBackground(new java.awt.Color(136, 184, 158));
        tablaSalaSolicitadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSalaSolicitadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaSalaSolicitadasMouseReleased(evt);
            }
        });
        scrollTablaSalasSolicitadas.setViewportView(tablaSalaSolicitadas);

        add(scrollTablaSalasSolicitadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void scrollTablaSalasSolicitadasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollTablaSalasSolicitadasMouseReleased
        try {
            int item = tablaSalaSolicitadas.getSelectedRow();
            int id = (int) tablaSalaSolicitadas.getValueAt(item, 0);
            Sala sala = dao.getDataSalas().obtenerSala(id);
//            if(sala.isDisponible()){
                String [] arreglo= {"No", "Si"};
                int opcion = JOptionPane.showOptionDialog(null, "Quiere devolver la sala "+sala.getNumeroSala(), "Devolver sala", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
                if(opcion == 1){
                    sala.setDisponible(true);
                    dao.getDataSalas().modificar(sala);
                    dao.getUsuarioSala().eliminar(app.getSesionActiva().getId(), sala.getNumeroSala());
                    actualizarTabla();
                }
//            }
//            else{
//                String [] arreglo= {"Ok"};
//                int opcion = JOptionPane.showOptionDialog(null, "sala "+sala.getNumeroSala()+" no disponible", "Elige otra sala", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
//            }
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_scrollTablaSalasSolicitadasMouseReleased

    private void tablaSalaSolicitadasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalaSolicitadasMouseReleased
        try {
            int item = tablaSalaSolicitadas.getSelectedRow();
            int id = (int) tablaSalaSolicitadas.getValueAt(item, 0);
            Sala sala = dao.getDataSalas().obtenerSala(id);
//            if(sala.isDisponible()){
                String [] arreglo= {"No", "Si"};
                int opcion = JOptionPane.showOptionDialog(null, "Quiere devolver la sala "+sala.getNumeroSala(), "Devolver sala", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
                if(opcion == 1){
                    sala.setDisponible(true);
                    dao.getDataSalas().modificar(sala);
                    dao.getUsuarioSala().eliminar(app.getSesionActiva().getId(), sala.getNumeroSala());
                    actualizarTabla();
                }
//            }
//            else{
//                String [] arreglo= {"Ok"};
//                int opcion = JOptionPane.showOptionDialog(null, "sala "+sala.getNumeroSala()+" no disponible", "Elige otra sala", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
//            }
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablaSalaSolicitadasMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollTablaSalasSolicitadas;
    private javax.swing.JTable tablaSalaSolicitadas;
    // End of variables declaration//GEN-END:variables
}
