/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Libro;
import model.Sala;
import model.tm.TMLibros;
import model.tm.TMSalas;
/**
 *
 * @author aniba
 */
public class SolicitarSala extends javax.swing.JPanel {

    /**
     * Creates new form SolicitarSala
     */
    App app;
    DAOManager dao = new DAOManager();
    public SolicitarSala(App appTemp) {
        initComponents();
        app = appTemp;
    }
    public void actualizarTabla(){
        try {
            ArrayList<Sala> salas = dao.getDataSalas().getSalas();
            TMSalas tm = new TMSalas(salas);
            tablaSalas.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarSala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subtitulo = new javax.swing.JLabel();
        pantallaSolicitarSala = new javax.swing.JPanel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaSalas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 490));
        setPreferredSize(new java.awt.Dimension(750, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("SOLICITAR SALA");
        add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        pantallaSolicitarSala.setBackground(new java.awt.Color(255, 255, 255));
        pantallaSolicitarSala.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollTabla.setBackground(new java.awt.Color(136, 184, 158));
        scrollTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                scrollTablaMouseReleased(evt);
            }
        });

        tablaSalas.setBackground(new java.awt.Color(136, 184, 158));
        tablaSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaSalasMouseReleased(evt);
            }
        });
        scrollTabla.setViewportView(tablaSalas);

        pantallaSolicitarSala.add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 390));

        add(pantallaSolicitarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void scrollTablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollTablaMouseReleased
        
    }//GEN-LAST:event_scrollTablaMouseReleased

    private void tablaSalasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalasMouseReleased
//        ArrayList<Sala> salas = dao.getDataSalas().getSalas()
        try {
            int item = tablaSalas.getSelectedRow();
            int id = (int) tablaSalas.getValueAt(item, 0);
            Sala sala = dao.getDataSalas().obtenerSala(id);
            if(sala.isDisponible()){
                String [] arreglo= {"No Solicitar", "Confirmar"};
                int opcion = JOptionPane.showOptionDialog(null, "sala "+sala.getNumeroSala()+" Disponible", "Confirmar Solicitud", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
                if(opcion == 1){
                    System.out.println("confirmanda");
                    sala.setDisponible(false);
                    dao.getDataSalas().modificar(sala);
                    dao.getUsuarioSala().agregarSala(sala.getNumeroSala(), app.getSesionActiva().getId());
                    actualizarTabla();
                }
            }
            else{
                String [] arreglo= {"Ok"};
                int opcion = JOptionPane.showOptionDialog(null, "sala "+sala.getNumeroSala()+" no disponible", "Elige otra sala", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
            }
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablaSalasMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pantallaSolicitarSala;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JTable tablaSalas;
    // End of variables declaration//GEN-END:variables
}
