/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.forms;

import app.App;
import db.DAOManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import model.Libro;
import model.tm.TMLibros;

/**
 *
 * @author aniba
 */
public class SolicitarLibro extends javax.swing.JPanel {

    /**
     * Creates new form SolicitarLibro
     */
    App app;
    DAOManager dao = new DAOManager();
    public SolicitarLibro(App appTemp) {
        initComponents();
        app = appTemp;
        
    }
    public SolicitarLibro() {
        initComponents();
    }
    
    public void actualizarTabla(){
        
        try {
            ArrayList<Libro> libros = dao.getDataLibros().getLibros();
            TMLibros tm = new TMLibros(libros);
            tablaDeLibros.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSolicitarLibro = new javax.swing.JPanel();
        scrollTablaLibros = new javax.swing.JScrollPane();
        tablaDeLibros = new javax.swing.JTable();
        boxCategoria = new javax.swing.JComboBox<>();
        nombreTitulo = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        panelSolicitarLibro.setBackground(new java.awt.Color(255, 255, 255));
        panelSolicitarLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeLibros.setBackground(new java.awt.Color(136, 184, 158));
        tablaDeLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDeLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaDeLibros.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        tablaDeLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaDeLibrosMouseReleased(evt);
            }
        });
        scrollTablaLibros.setViewportView(tablaDeLibros);

        panelSolicitarLibro.add(scrollTablaLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 749, 450));

        boxCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        boxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ficción", "No ficción", "Literatura clásica", "Ciencia ficción", "Fantasía", "Misterio y suspense", "Thriller", "Romántico", "Biografía y memorias", "Historia", "Ensayo", "Poesía", "Literatura juvenil", "Cuentos y relatos cortos" }));
        boxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxCategoriaMouseClicked(evt);
            }
        });
        panelSolicitarLibro.add(boxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 5, 130, 30));

        nombreTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nombreTitulo.setForeground(new java.awt.Color(153, 153, 153));
        nombreTitulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombreTitulo.setText("Nombre del Libro");
        nombreTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombreTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombreTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nombreTituloMouseReleased(evt);
            }
        });
        nombreTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTituloKeyTyped(evt);
            }
        });
        panelSolicitarLibro.add(nombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 440, 30));

        labelCategoria.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelCategoria.setText("Categoria: ");
        panelSolicitarLibro.add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 5, 70, 30));

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        labelTitulo.setText("Titulo:");
        panelSolicitarLibro.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelSolicitarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelSolicitarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaDeLibrosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDeLibrosMouseReleased
        try {
            int item = tablaDeLibros.getSelectedRow();
            int id = (int) tablaDeLibros.getValueAt(item, 0);
            Libro libro = dao.getDataLibros().obtenerLibro(id);
            Detalleslibro detalles = new Detalleslibro(app);
            app.setPanelCustom2(detalles);
            detalles.setLibro(libro);
            System.out.println(libro.toString());
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablaDeLibrosMouseReleased

    private void nombreTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTituloKeyTyped
        try {
            ArrayList<Libro> libros = dao.getDataLibros().filtroTitulo(nombreTitulo.getText());
            TMLibros tm = new TMLibros(libros);
            tablaDeLibros.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nombreTituloKeyTyped

    private void nombreTituloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTituloMouseReleased
        nombreTitulo.setText("");
    }//GEN-LAST:event_nombreTituloMouseReleased

    private void boxCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxCategoriaMouseClicked
        String categoria = String.valueOf(boxCategoria.getSelectedItem());
        try {
            ArrayList<Libro> libros = dao.getDataLibros().filtroCategoria(categoria);
            TMLibros tm = new TMLibros(libros);
            tablaDeLibros.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(SolicitarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boxCategoriaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCategoria;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField nombreTitulo;
    private javax.swing.JPanel panelSolicitarLibro;
    private javax.swing.JScrollPane scrollTablaLibros;
    private javax.swing.JTable tablaDeLibros;
    // End of variables declaration//GEN-END:variables
}
